[package]
name = "advent20"
version = "0.1.0"
authors = ["arborelia <gh@arborelia.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scan_fmt = "0.2.5"
defaultmap = "0.5.0"
array2d = "0.2.1"